feature(#107) : JWT refresh token 구현
softeerbootcamp/Team1-TDD pull request #111
Opened 2023-02-12 01:53 UTC by psm9718

### 이슈 넘버
- resolved #107 

### 이런 이유로 코드를 변경했어요
- JWT 액세스 토큰만으로는 보안 상 좋지 않다고 알고 있었는데, 실제로 구현해보니 정말 그렇다는 생각이 들어 refresh token 기능을 추가하여 기능의 완성도를 높였습니다.

### 이런 작업을 했어요
- 이제 로그인 시 ATK (Access Token) 과 RTK (Refresh Token)으로 응답하며, 토큰의 역할과 상태는 enum처리하였습니다.
- 인증 시 동일하게 ATK만 Authroization 헤더에 넣어서 보내주시면 됩니다.
- **인증 만료시 바로 로그인 요청이 되는 것이 아닌 refresh token을 가지고 redirect되어야 합니다 (별도로 설명드리겠습니다.)**
- JWT 토큰 안에 들어 있는 정보가 userId 로 변경되어 클라이언트와 서버 간 유저 정보를 가져오기 용이하도록 하였습니다.

### 리뷰어는 여기에 집중해주시면 좋아요
- token 발급 & 인증 관련된 부분과 user 관련한 로직을 분리하고 패키지 구조를 리팩토링해야하는데 완전 분리하려니 애매한 부분이 있기도 해서 고민이 됩니다.
- 자세한 JWT의 이론적인 과정은 Discussion에 정리해두었습니다. (https://github.com/softeerbootcamp/Team1-TDD/discussions/100) 
- 저장용으로 작성하다보니 읽기 불편하실 수 있습니다. 자세한 동작 과정은 회의 때 말씀 드리며, 필요 시 별도 문서화하여 git wiki에 첨부하겠습니다.

### ❗ dev에 올라가기 전에 yml 파일을 수정해야 정상적으로 동작합니다! 
### ❗ 현재 구현에서는 액세스 토큰 만료 시 refresh 토큰을 요청하여 redirect 처리하는 부분이 구현되어 있지 않습니다! 프론트 분들과 이야기하고 최종 구현해서 배포하는게 좋을 듯 합니다.

2023-02-12 02:10 UTC, River-Mt approved these changes

2023-02-12 02:10 UTC, River-Mt commented on back-end/src/main/java/com/tdd/backend/user/UserController.java
> +		return ResponseEntity.ok(userService.reIssueToken(refreshToken));
.body()를 안쓰고 .ok() 안에 인자로 바디를 넣어도 전달이 되는군요

2023-02-12 02:10 UTC, River-Mt commented on back-end/src/main/java/com/tdd/backend/user/UserController.java
> +	@PostMapping("/reissue")
reissue가 무슨 의미인가요?

2023-02-12 02:10 UTC, River-Mt commented on back-end/src/main/java/com/tdd/backend/user/UserService.java
> +			// ATK 재발급은 RTK의 payload에서 유저의 email을 꺼낸 뒤, Redis 인메모리에 해당 유저의 존재 유무로 결정된다.
email? id? 뭐가 키인가요?

2023-02-12 03:00 UTC, psm9718 commented on back-end/src/main/java/com/tdd/backend/user/UserService.java
> +			// ATK 재발급은 RTK의 payload에서 유저의 email을 꺼낸 뒤, Redis 인메모리에 해당 유저의 존재 유무로 결정된다.
id입니다! id로 하면 이제 클라이언트에 user id가 노출되지 않고도 통신할 수 있을 것 같아요

2023-02-12 03:01 UTC, psm9718 commented on back-end/src/main/java/com/tdd/backend/user/UserController.java
> +	@PostMapping("/reissue")
재발급을 의미합니다!

2023-02-12 03:02 UTC, psm9718 commented on back-end/src/main/java/com/tdd/backend/auth/RefreshTokenStorage.java
> + * key : email
앗 맞습니다 리팩토링이 덜되었네요 수정하겠습니다

2023-02-12 03:02 UTC, psm9718 commented on back-end/src/main/java/com/tdd/backend/auth/JwtTokenPairResponse.java
> +	private JwtTokenPairResponse(String accessToken, String refreshToken) {
헉 그런가요? 저는 원래는 롬복으로 protected 설정해두고 사용해왔었긴 한데 그럼 생성자를 보통 public으로 열어두는가요??

2023-02-12 05:11 UTC, MyuB approved these changes
고생하셨습니다.

2023-02-12 05:21 UTC, River-Mt commented on back-end/src/main/java/com/tdd/backend/auth/JwtTokenPairResponse.java
> +	private JwtTokenPairResponse(String accessToken, String refreshToken) {
더 알아보고 월요일 회의 때 말씀드릴게요!!

2023-02-12 05:21 UTC, River-Mt commented on back-end/src/main/java/com/tdd/backend/user/UserService.java
> +			// ATK 재발급은 RTK의 payload에서 유저의 email을 꺼낸 뒤, Redis 인메모리에 해당 유저의 존재 유무로 결정된다.
그럼 여기 주석도 email -> id 로 바꿔야하는게 맞나요?

2023-02-12 05:56 UTC, jieonkim23 reviewed
와 refresh token까지!! 수고하셨습니다

2023-02-12 06:03 UTC, jieonkim23 commented on back-end/src/main/java/com/tdd/backend/auth/AuthResolver.java
> +		if (jwtTokenStatus.equals(ACCESS)) {
enum function 오버라이딩이나 스위치문으로 리팩토링 가능할 것 같아요!

2023-02-12 06:12 UTC, jieonkim23 commented on back-end/src/main/java/com/tdd/backend/user/UserService.java
> +		String refreshToken = jwtTokenProvider.generateRefreshToken(user.getId());
유저아이디로 모두 수정되었군요..! 감사합니다!

2023-02-12 06:13 UTC, jieonkim23 approved these changes
주말인데 고생하셨습니다!

2023-02-12 14:08 UTC, 2je0 requested changes
아직 dev에 머지하지 말아주세요!!!!!!!!!!!!

2023-02-12 14:23 UTC, psm9718 commented
> 아직 dev에 머지하지 말아주세요!!!!!!!!!!!!

네네 ㅎㅎ 화이팅이에요💪 💪

2023-02-12 15:01 UTC, 2je0 commented
> > 아직 dev에 머지하지 말아주세요!!!!!!!!!!!!
> 
> 네네 ㅎㅎ 화이팅이에요💪 💪

엇 근데 승민님 이 브랜치 지금 충돌나고 있는건가요??

2023-02-12 21:44 UTC, psm9718 commented
> > > 아직 dev에 머지하지 말아주세요!!!!!!!!!!!!
> > 
> > 
> > 네네 ㅎㅎ 화이팅이에요💪 💪
> 
> 엇 근데 승민님 이 브랜치 지금 충돌나고 있는건가요??

충돌 확인하려고 pull 받았는데 충돌이 안나서(??) 다시 푸쉬했어요! 이제 괜찮을 겁니다 허허

2023-02-13 01:23 UTC, 2je0 approved these changes

2023-02-13 01:24 UTC, merged