feature(#136) Redis DB에 RTK 값 cache 구현
softeerbootcamp/Team1-TDD pull request #144
Opened 2023-02-13 11:48 UTC by psm9718

### 이슈 넘버
- resolved #136 

### 이런 이유로 코드를 변경했어요
- 기존 HashMap 형태로 cache되었던 Refresh Token을 Redis를 통해 성능을 높이고 기술적 도전을 하고자 하였습니다.
- RedisTemplate을 연결하는 DAO인 `RefreshTokenService` 를 빈 등록하기 때문에 전역적으로 호출될 때에 비해 user 도메인 로직에서 역할을 분리하고 리팩토링할 필요를 느꼈습니다.

### 이런 작업을 했어요
- HahMap 형태로 전역적으로 호출되던 `RefreshTokenStorage` 클래스를 ``RedisTemplate` 으로 개선하였습니다.
- user 도메인 내에 UserController와 함께 `AuthController` 로 클래스를 분리하여 토큰 관련 이슈를 해결하도록 클래스를 분리했습니다.

### 리뷰어는 여기에 집중해주시면 좋아요
- 리팩토링된 패키지 구조에 대해 확인해보시고 피드백 남겨주시면 좋겠습니다.
- Redis에 대해 살펴보시고 피드백 남겨주시면 좋겠습니다.

### ❗ 배포환경에서의 Redis 세팅 완료 후 머지해야 서버에 장애가 나지 않습니다. 한 번 더 체크해보도록 하겠습니다. 

### 이런 위험이나 장애가 있어요
- Redis를 처음 사용해봐서 로컬에서는 테스트를 마쳤는데 배포 단계에서 예기치 못한 장애가 발생할 위험이 있습니다. 오류 발견 시 언제든 말씀해주세요!

### 향후 이런 계획이 있어요
- 배포 후 Redis 성능에 대한 테스트와 개선이 필요할 것 같습니다.

2023-02-13 11:58 UTC, River-Mt requested changes
서버에 Redis 세팅 완료 시 알려주세요!

2023-02-13 11:58 UTC, River-Mt commented on back-end/src/main/java/com/tdd/backend/user/controller/AuthController.java
> +		@RequestHeader("Authorization") String refreshToken) {
@RequestHeader가 어떤 역할인지 궁금합니다.

2023-02-14 01:18 UTC, psm9718 commented on back-end/src/main/java/com/tdd/backend/user/controller/AuthController.java
> +		@RequestHeader("Authorization") String refreshToken) {
`@RequestHeader` 애노테이션은 해당 컨트롤러로 들어오는 HTTP 요청 메시지에서 value ("Authorization") 에 해당하는 헤더 값을 가져올 수 있습니다. 이는 default가 true여서 HTTP 요청 메시지에 그 헤더가 존재하지 않으면 400에러를 반환합니다.

2023-02-14 01:53 UTC, River-Mt approved these changes

2023-02-15 09:21 UTC, merged