Be/performance/#192 email async
softeerbootcamp/Team1-TDD pull request #196
Opened 2023-02-18 06:55 UTC by psm9718

### 이슈 넘버
- resolved #192 

### 이런 이유로 코드를 변경했어요
- 메일 전송 완료를 기다리기 위해 클라이언트가 응답을 늦게 받는 상황을 없애고 싶었고, 그러기 위해 비동기 처리를 도입하게 되었습니다.

### 이런 작업을 했어요
- 메일 알람 서비스에 대해 로직 수행이 완료되기 까지 로컬 기준 약 7초 정도의 시간이 소요되었는데, 비동기 처리를 통해 로직이 완료되기 이전에 메일을 즉각적으로 받을 수 있도록 하였습니다.

### 리뷰어는 여기에 집중해주시면 좋아요
- ❗ (중요) 메일 전송 로직을 DrivingService 클래스에서 수행하는 것으로 바꾸었는데, 머지 과정에서 충돌이 나서 병합하였습니다. 테스트는 통과하였지만 `DrivingService` 클래스 혹시나 병합 과정에서 잘못한 부분이 없는지 확인 부탁드립니다!!
- 비동기 처리가 정상적으로 작동되며, 성능 개선이 일어났는지 테스트해보기 어려워 좋은 아이디어가 있다면 말씀해주시면 감사하겠습니다.
- 이메일의 경우, AOP 처리를 해서 클래스로부터 관심사를 분리하는 방법이 존재하는데, 이 부분은 추후 기능 구현이 모두 완료된 시점에 고려해보면 좋을 것 같습니다!
관련 링크 : https://supawer0728.github.io/2018/03/24/spring-event/

### 이런 위험이나 장애가 있어요
- 배포환경에서도 이메일이 정상적으로 발송되는지 확인이 필요합니다.

### 스크린샷
<img width="1482" alt="스크린샷 2023-02-18 오후 3 53 00" src="https://user-images.githubusercontent.com/60373714/219846166-be8f18b1-6400-464b-90b5-dca3358bf9e9.png">

2023-02-18 06:56 UTC, River-Mt commented
PR이름 변경해주세요!

2023-02-18 07:12 UTC, River-Mt commented on back-end/src/main/java/com/tdd/backend/post/service/DrivingService.java
> +	public static class AppointmentAcceptEvent {
inner class로 만든 이유가 있을까요?

2023-02-18 07:13 UTC, River-Mt approved these changes

2023-02-18 12:32 UTC, River-Mt requested changes
오류가 있다고 하셔서 Request changes합니다.

2023-02-18 23:29 UTC, psm9718 commented on back-end/src/main/java/com/tdd/backend/post/service/DrivingService.java
> +	public static class AppointmentAcceptEvent {
별도의 EventListener 클래스로 메일 전송 로직을 클래스 분리하고자 하는 과정에서 사용하는 DTO였으나 현재는 삭제되었습니다.

2023-02-18 23:30 UTC, psm9718 commented
비동기 처리 해결되었습니다! 시간적인 여유가 된다면 AOP처리까지 진행해서 예약 관련 로직과 메일 전송 로직을 분리하고 싶습니다!

2023-02-19 02:05 UTC, River-Mt approved these changes
어느 부분 때문에 오류가 났었고 어떻게 해결하셨는지가 궁금해요

2023-02-19 03:38 UTC, psm9718 commented
> 어느 부분 때문에 오류가 났었고 어떻게 해결하셨는지가 궁금해요

부끄러운 설정 오류였습니다 하하 레퍼런스를 꼼꼼히 읽자 정도로.. 해결했습니다.. 😅

2023-02-19 10:59 UTC, jieonkim23 approved these changes
주말인데 고생하셨습니다!

2023-02-19 10:59 UTC, jieonkim23 commented on back-end/src/main/java/com/tdd/backend/mail/service/MailService.java
>  		}
예외처리를 해야겠네요 사실 제가 해놨어야했는데... 부탁드리겠습니다

2023-02-19 10:59 UTC, jieonkim23 commented on back-end/src/main/java/com/tdd/backend/mail/service/MailService.java
> +	public EmailMessage generateEmailMessage(PostInfo postInfo, Long FromId, Long toId, UserType userType) {
변수명이 아름답게 바뀌었군요..! 저도 고민하다가 another한거였는데 왜 from to를 생각못했을까요? 아무튼 좋습니다!

2023-02-19 10:59 UTC, jieonkim23 commented on back-end/src/main/java/com/tdd/backend/config/AsyncConfig.java
> +@Configuration
어노테이션이 빠져있어서 오류가 났던 건가요? 그렇다면 별거 아니었던 문제라 정말 다행입니다

2023-02-19 10:59 UTC, jieonkim23 commented on back-end/src/main/java/com/tdd/backend/post/controller/DrivingController.java
> +
컨트롤러에서 서비스 2개를 호출하는 방식에서 dirveservice에서 mailservice를 호출하도록 변경하신 것 같은데 연유가 궁금합니다!

2023-02-19 14:06 UTC, psm9718 commented on back-end/src/main/java/com/tdd/backend/mail/service/MailService.java
>  		}
앗 근데 이런 예외도 custom 예외를 따로 만들어야 하나에 대한 생각이 갑자기 들긴 하네요... 일단 월요일에 한번 이야기해보죠!

2023-02-19 14:06 UTC, psm9718 commented on back-end/src/main/java/com/tdd/backend/post/controller/DrivingController.java
> +
컨트롤러와 서비스의 역할은 고민이 되는 부분인데, 저는 컨트롤러의 역할을 아래 3가지로 생각합니다.

1. 클라이언트로부터 적절한 형태로 요청받기
2. 비즈니스 로직을 서비스에게 위임
3. 서비스 로직 결과로 다시 클라이언트에게 적절한 형태로 응답하기

여기서 메일 전송은 2번의 서비스로직으로 생각되기도 했으며, 개인적으로 서비스가 좀 복잡해지더라도 컨트롤러가 API 요청 응답 정보만 담도록 깔끔한 것을 더 선호해서 변경하였습니다!

2023-02-19 14:06 UTC, psm9718 commented on back-end/src/main/java/com/tdd/backend/config/AsyncConfig.java
> +@Configuration
맞습니다..깔깔 멍청한 오류였습니다 하하 정신이 없었네요..

2023-02-19 14:06 UTC, psm9718 commented on back-end/src/main/java/com/tdd/backend/config/AsyncConfig.java
> +		return executor;
넵 수치는 레퍼런스를 참고하였습니다!

2023-02-19 14:07 UTC, merged